#:schema node_modules/wrangler/config-schema.json
name = "with-hyperdrive"
main = "src/index.ts"
compatibility_date = "2024-12-05"
compatibility_flags = ["nodejs_compat"]
# wrangler.toml (wrangler v3.88.0^)
[observability.logs]
enabled = true
[[hyperdrive]]
binding = "HYPERDRIVE"
id = "279c708c1c1747d7ada5f1fe31c0df8f"
