version: "3.9"

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_DB=plazacms
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=SuperSecret
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  postgrest:
    image: postgrest/postgrest:latest
    container_name: postgrest_api
    restart: always
    depends_on:
      - db
    environment:
      - PGRST_DB_URI=postgres://admin:SuperSecret@db:5432/plazacms
      - PGRST_DB_SCHEMA=public
      - PGRST_DB_ANON_ROLE=admin
    ports:
      - "3000:3000"

volumes:
  pgdata:
