name = "admin-hono"
main = "src/index.ts"
compatibility_date = "2024-12-18"
compatibility_flags = ["nodejs_compat"]

# Development server configuration
[dev]
port = 1945

[observability.logs]
enabled = true



# Environment variables
[vars]
ADMIN_EMAIL = "agatekarin@gmail.com"
AUTH_SECRET = "a41472ad95172231e24b36db3cd45ae42e317ecc5f9872a002ab736d32ba1d49"
# auth_url is use nextjs frontend url which is 3001
AUTH_URL = "http://localhost:3001/api/authjs"
R2_PUBLIC_URL = "https://img.plazaku.my.id"
# Optional: enable Cloudinary fetch optimization on backend responses
CLOUDINARY_CLOUD_NAME = "dg4otwgak" # e.g. "your-cloud-name"

# ====================================================================
# EMAIL SYSTEM CONFIGURATION
# ====================================================================

# Store branding
STORE_NAME = "PlazaCMS Demo"

# FROM_EMAIL Configuration:
# 🔥 DEVELOPMENT: Use Resend sandbox emails (no domain verification needed)
FROM_EMAIL = "onboarding@resend.dev"
# Alternative sandbox emails: delivered@resend.dev, notifications@resend.dev

# 🚀 PRODUCTION: Use your verified domain (requires DNS setup at https://resend.com/domains)
# FROM_EMAIL = "noreply@yourdomain.com"  # Uncomment & replace when domain is verified

# Frontend URL (NextJS Admin runs on port 3001)
FRONTEND_URL = "http://localhost:3001"

# Secrets (set via wrangler secret put)
JWT_SECRET = "a41472ad95172231e24b36db3cd45ae42e317ecc5f9872a002ab736d32ba1d49"
RESEND_API_KEY = "re_Bc4Q9KDa_KWRZBaNaVbTXQxhsfPqgjW8j" # Set via: wrangler secret put RESEND_API_KEY

# For development phase
DISABLE_RATE_LIMIT=1

# Hyperdrive configuration
[[hyperdrive]]
binding = "HYPERDRIVE"
id = "279c708c1c1747d7ada5f1fe31c0df8f"
localConnectionString = "postgres://admin:SuperSecret@localhost:5432/plazacms"

# R2 bucket binding for media uploads
[[r2_buckets]]
binding = "R2"
bucket_name = "agatekarin"
# preview_bucket_name = "agatekarin-dev"

# Rate Limiting storage (Workers KV)
[[kv_namespaces]]
binding = "RATE_LIMIT_KV"
id = "1a7e662eb5904a6ab7653751b0fbabfd" # TODO: replace with your KV namespace id