name = "admin-hono"
main = "src/index.ts"
compatibility_date = "2024-12-18"
compatibility_flags = ["nodejs_compat"]

[observability.logs]
enabled = true

# Environment variables
[vars]
ADMIN_EMAIL = "admin@local"
AUTH_SECRET = "a41472ad95172231e24b36db3cd45ae42e317ecc5f9872a002ab736d32ba1d49"
AUTH_URL = "http://localhost:3001/api/authjs"
R2_PUBLIC_URL = "https://img.plazaku.my.id"
# Optional: enable Cloudinary fetch optimization on backend responses
CLOUDINARY_CLOUD_NAME = "dg4otwgak" # e.g. "your-cloud-name"

# Secrets (set via wrangler secret put)
JWT_SECRET = "a41472ad95172231e24b36db3cd45ae42e317ecc5f9872a002ab736d32ba1d49"

# Hyperdrive configuration
[[hyperdrive]]
binding = "HYPERDRIVE"
id = "279c708c1c1747d7ada5f1fe31c0df8f"
localConnectionString = "postgresql://neondb_owner:npg_aIuy0lwEGJ8S@ep-long-wildflower-ae91z3hf.c-2.us-east-2.aws.neon.tech/neondb"

# R2 bucket binding for media uploads
[[r2_buckets]]
binding = "R2"
bucket_name = "agatekarin"
# preview_bucket_name = "agatekarin-dev"

# Rate Limiting storage (Workers KV)
[[kv_namespaces]]
binding = "RATE_LIMIT_KV"
id = "1a7e662eb5904a6ab7653751b0fbabfd" # TODO: replace with your KV namespace id